"""Generate ro/index.html (Romanian) from index.html (English) + i18n.js (Romanian texts).

Run after any change to index.html or i18n.js:   python build-ro.py
Standard library only. Fails loudly if a key is missing so the RO page never silently drifts.
"""
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).parent
SITE = "https://datumconsultancy.com"

src = (ROOT / "index.html").read_text(encoding="utf-8")
i18n = (ROOT / "i18n.js").read_text(encoding="utf-8")

RO = {k: json.loads(v) for k, v in re.findall(r'^\s*(k\d+): (".*?"),', i18n, re.M)}
META = {k: json.loads(v) for k, v in re.findall(r'^\s*(\w+): (".*?"),', i18n.split("const RO = {")[0], re.M)}


def replace_inner(html, key, new_inner):
    """Swap the inner HTML of the element carrying data-i18n="key" (handles nested same-name tags)."""
    m = re.search(r'<(\w+)\b[^>]*\bdata-i18n="%s"[^>]*>' % key, html)
    if not m:
        raise SystemExit(f"index.html has no element with data-i18n=\"{key}\"")
    tag, start = m.group(1), m.end()
    depth, pos = 1, start
    for t in re.finditer(r"<(/?)%s\b[^>]*>" % tag, html[start:]):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            end = start + t.start()
            return html[:start] + new_inner + html[end:]
        pos = t.end()
    raise SystemExit(f"unclosed <{tag}> for {key}")


keys_in_html = set(re.findall(r'data-i18n="(k\d+)"', src))
missing = sorted(keys_in_html - RO.keys(), key=lambda k: int(k[1:]))
if missing:
    raise SystemExit("Missing Romanian text in i18n.js for: " + ", ".join(missing))

out = src
for key in keys_in_html:
    out = replace_inner(out, key, RO[key])


def sub(old, new, count=1):
    global out
    if old not in out:
        raise SystemExit(f"build-ro.py: expected text not found: {old[:60]}")
    out = out.replace(old, new, count)


# document language + head
sub('<html lang="en">', '<html lang="ro">')
out = re.sub(r"<title>.*?</title>", "<title>%s</title>" % META["title"].replace("&", "&amp;"), out, 1)
out = re.sub(r'(<meta name="description" content=")[^"]*', r"\g<1>" + META["description"].replace("&", "&amp;"), out, 1)
out = re.sub(r'(<meta property="og:title" content=")[^"]*', r"\g<1>" + META["ogTitle"], out, 1)
out = re.sub(r'(<meta property="og:description" content=")[^"]*', r"\g<1>" + META["ogDescription"], out, 1)
sub(f'<link rel="canonical" href="{SITE}/">', f'<link rel="canonical" href="{SITE}/ro/">')
sub(f'<meta property="og:url" content="{SITE}/">', f'<meta property="og:url" content="{SITE}/ro/">')
sub('<meta property="og:locale" content="en_US">\n  <meta property="og:locale:alternate" content="ro_RO">',
    '<meta property="og:locale" content="ro_RO">\n  <meta property="og:locale:alternate" content="en_US">')

# relative paths: this page lives one folder deeper
out = re.sub(r'(href|src)="(?!https?:|mailto:|tel:|#|\.\./|/)(styles\.css|script\.js|lang\.js|assets/)', r'\1="../\2', out)

# language switch: RO is now the current page
sub('<a href="./" hreflang="en" lang="en" data-lang="en" aria-current="true"', '<a href="../" hreflang="en" lang="en" data-lang="en"')
sub('<a href="ro/" hreflang="ro" lang="ro" data-lang="ro"', '<a href="./" hreflang="ro" lang="ro" data-lang="ro" aria-current="true"')

# labels and WhatsApp pre-filled message
sub('aria-label="Open menu"', f'aria-label="{META["menu"]}"')
sub('aria-label="Chat on WhatsApp"', f'aria-label="{META["wa"]}"')
sub('alt="Andrei, founder of Datum Consulting"', f'alt="{META["portrait"]}"')
out = re.sub(r'https://wa\.me/40743963758\?text=[^"]*', "https://wa.me/40743963758?text=" + quote(META["waText"]), out)

banner = "<!-- GENERATED by build-ro.py from index.html + i18n.js. Do not edit by hand. -->\n"
(ROOT / "ro").mkdir(exist_ok=True)
(ROOT / "ro" / "index.html").write_text(out.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1), encoding="utf-8")
print(f"ro/index.html written ({len(keys_in_html)} texts translated)")
